image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  #  - java -jar ./artifacts/app-deadline.jar -P:profile=ru.netology.test &
  - Container start
  - docker-compose up &
  - Waiting for сontainer start
  - sleep 30
  - java -jar ./artifacts/app-deadline.jar -P:jdbc.url=jdbc:mysql://localhost:3306/db &
  - chmod +x gradlew
build_script:
  - ./gradlew ru.netology.test --info -Dselenide.headless=true